### ISSUE TITLE
Exception has occurred. UnimplementedError

### ISSUE THREAD

**Issue by muhammadumairghaznavi** [shashiben/portfolio#11]
The app is not working and continuously showing errors
![image](https://user-images.githubusercontent.com/85787407/192109330-db1738cd-86e5-417a-9c4c-9a2d7d8ec6cc.png)

Please see the error below. And let me know how I can solve this issue on every page.
Exception has occurred. UnimplementedError

**Comment by shashiben** [comment]
https://github.com/google/vector_math.dart/issues/212


Try with double like (0.0,1.0)

**Comment by muhammadumairghaznavi** [comment]
> [google/vector_math.dart#212](https://github.com/google/vector_math.dart/issues/212)
> 
> Try with double like (0.0,1.0)

Oh thank you my brother. THanks very much. Lots of love bro.
